# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# as.py
# Created on: 2013-06-27 02:52:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
Multiple_Value = "'F:\\Survey\\Mussoorie\\Test For Automation back to arcgis\\CH_SeisVARA-INTENSITY.xls';'F:\\Survey\\Mussoorie\\Test For Automation back to arcgis\\CL_SeisVARA-INTENSITY.xls';'F:\\Survey\\Mussoorie\\Test For Automation back to arcgis\\CM_SeisVARA-INTENSITY.xls'"

# Process: Iterate Multivalue
arcpy.IterateMultivalue_mb(Multiple_Value)

